name: Docker Image CI
on:
  push:
    branches:
    - 'feat/*'
    - 'fix/*'
    - 'chore/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr '[|/]' '-')"
      id: extract_branch
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag germainlefebvre4/bspauto-scraper:${{ steps.extract_branch.outputs.branch }}
    - name: Test run container - Run python script
      run: docker run --rm germainlefebvre4/bspauto-scraper:${{ steps.extract_branch.outputs.branch }}
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: germainlefebvre4/bspauto-scraper:${{ steps.extract_branch.outputs.branch }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

